#pragma config(Motor,  port2,           LFmotor,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LRmotor,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           RRmotor,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           winch,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           laucher1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RFmotor,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           laucher2,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           laucher34,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          laucher56,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

short autoMode;

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "Drive.c"
#include "RTTTL.c"



void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks runningbetween
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;
  autoMode = 0;
	// initialize the system....

	bLCDBacklight = true;
}


task autonomous()
{

	switch(autoMode)
	{
		case 0:
			Autonomous1();
			break;

		}


}

task usercontrol()
{

	startTask(speedControl,150);

	while(1)
	{
	if(vexRT(Btn8LXmtr2) == 1)
  {
		playYaketysax();
  }

  	if(vexRT(Btn8U) == 1)
  {
		playYaketysax();
  }

	if(vexRT[Btn8RXmtr2] == 1)
	{
		playAxelF();
	}

	if(vexRT[Btn8UXmtr2] == 1)
	{
		playStarWars();
	}

	if(vexRT(Btn8DXmtr2) == 1)
	{
		playMissionImpossible();
	}

	Drive();
  }
}
